POST http://localhost:3000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxLCJlbWFpbEFkZHJlc3MiOiJtYXRAZ21haWwuY29tIiwiZXhwIjoxNzI5MDU2MDI1fQ.9pX7sPAwTBiTptz95qtVUBeVxKz7elmnUt5ReDi1KCo

{
    "name": 4,
    "description": "This is a test event",
    "location": "http://localhost",
    "dateTime": "2023-01-01T15:30:00.000Z"
}