GET http://localhost:3000/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjo0LCJlbWFpbEFkZHJlc3MiOiJtYXRAZ21haWwuY29tIiwiZXhwIjoxNzE5NTA5ODIxfQ.eCnrw6XcTXKRvNFZH5qb5J_j4KRuTSA3pmwrPa5qLw8
