GET http://localhost:3000/events/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcklkIjoxLCJlbWFpbEFkZHJlc3MiOiJtYXRAZ21haWwuY29tIiwiZXhwIjoxNzI5MDU2MDI1fQ.9pX7sPAwTBiTptz95qtVUBeVxKz7elmnUt5ReDi1KCo